### ISSUE TITLE
Confusion about next steps after installation

### ISSUE THREAD

**Issue by Ahrengot** [OEvgeny/bootstrap-postcss#5]
Hey @OEvgeny!

Awesome initiative to build a script that automatically converts the latest bootstrap files. I'm a little confused about next steps after cloning bootstrap and running the npm commands. Is it the .scss files in `postcss` I'm supposed to rename .css and move to my other styles folder? How do i include the styles in my projects base `main.css` file?

**Comment by OEvgeny** [comment]
In short: don't do that. At first because both: bootstrap 4 and this project are at the early stage of development.

I did't rename files because it is not needed. The plugin that used for `@import` handles this correctly.

There are some issues with build.  Also, there are failed tests (and I have no idea how to fix it).

So, you can play with it and contribute, but you can't use it for development at the moment.
